/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 dragonFountain.glb 
Author: HoangHiepVu (https://sketchfab.com/HoangHiepVu)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/fountain-with-a-dragon-in-nikko-japan-453d616370cd42c4ae217ae3c2f401ed
Title: Fountain with a dragon in Nikko, Japan
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

const Dragon = (props) => {
  const { nodes, materials } = useGLTF("models/dragonFountain.glb");
  return (
    <group {...props} dispose={null}>
      <group position={[0, 1.509, -0.353]} rotation={[-Math.PI, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.Model_0} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.Model_0} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.Model_0} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.Model_0} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.Model_1} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.Model_1} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.Model_1} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.Model_1} />
      </group>
    </group>
  );
};

useGLTF.preload("models/dragonFountain.glb");
export default Dragon;
